### ISSUE TITLE
구글번역 새로운 알고리즘 ‘NMTS’, 인간과 기계번역 차이 연결

### ISSUE THREAD

**Issue by hyungtaecf** [10alswhd/BlueHouseProject#73]
구글이 새로운 알고리즘을 이용해 까다롭기로 유명한 ‘중국어-영어 번역’ 서비스 오류를 약 60%까지 줄인 것으로 나타났다.

http://www.itnews.or.kr/?p=19673

**Comment by satin1004** [comment]
같은글이 연달아 2개 올라왔네요 ㅋㅋ
